chore(refactor): refactored legacy codes for server
MilanCommunity/Milan-Backend pull request #28
Opened 2023-09-30 21:19 UTC by cu8code

chore(refactor): refactored legacy codes for server.

closes #27 

### 👷🏻 Changes made  
refactor code to use Status code & Status message.

2023-10-05 04:43 UTC, cu8code commented
@tamalCodes please review this

2023-10-06 06:34 UTC, tamalCodes requested changes
- Alot of places are still using messages like `message: "Internal Server Error"` instead of that they can use `STATUSMESSAGE.INTERNAL_SERVER_ERROR` 
 - Make sure all the places are using `STATUSCODE` and `STATUSMESSAGE` except for those which has custom messages.

With those changes done, we would be good to go.
Sorry about the delay.

2023-10-06 06:34 UTC, tamalCodes commented on routes/user/Auth.js
> +      return res.status(STATUSCODE.NOT_FOUND).json({ message: "User not found" });
```suggestion
      return res.status(STATUSCODE.NOT_FOUND).json({ message: STATUSMESSAGE.USER_NOT_FOUND });
```

2023-10-19 06:05 UTC, tamalCodes commented
# Notice 🚩

Hi there, unfortunately, I will have to close this Issue/PR, as this issue/PR has been inactive for quite a while and there's no work going on for the same.

There might be more Issues/PR that are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before marking any issue as stale and closing it.

If you think that this is a mistake, please drop an email at milanhub.org@gmail.com, and we will get back to you.

Regards, 
Team Milan.

2023-10-19 06:05 UTC, closed without merging